version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transparent_pipeline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: tp_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_data:
